language: node_js
node_js: stable

cache:
  directories:
    - node_modules
    # The `next-door` from `hengliang.github.hexo-theme-next`
    - themes/next-door

install:
  - npm install
  - npm install --save-dev

before_script:  
  - rm -rf themes
  - git clone https://github.com/Hengliang/hexo-theme-next.git --branch hengliang@develop.remote themes/next-door
  - sed -i -e 's/#\[GA_TOKEN\]/${GA_TOKEN}/g' _config.yml
  - sed -i -e 's/#\[LEANCLOUD_ID\]/${LEANCLOUD_ID}/g' _config.yml
  - sed -i -e 's/#\[LEANCLOUD_KEY\]/${LEANCLOUD_KEY}/g' _config.yml

script:
  - gulp build

after_success:
  - cd public
  - git init
  - git config user.name "hengliang"
  - git config user.email "hengliang.jia@gmail.com"
  - git add .
  - git commit -m "Travis CI build"
  - git push --force "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master
  # if it isn't a user/org page, please replace it with <master:gh-pages>
  

branches:
  only:
    - master

# Travis Environment Variables Guild
# https://docs.travis-ci.com/user/environment-variables
env:
  global:
    # GIT_PAGE_REF
    - GIT_PAGE_REF: github.com/Hengliang/hengliang.github.io
    # GH_TOKEN
    - secure: "Hf7FFzn4sk1mFPkrZj/BQLlz436LdJz25oHArcoTJqenXNFmXYKh1+aRi1D4SyjEm+jHyasc0u4jB+YA40QUEo0A+u8ZXhBw4gq5St5SvaniELoMycQ6QCVxHl2dKZItQ6YZmrMPwHh6yOfShJgYA4IwUfMDTG2u/+7tXmRNcff4usR38Vbl4F52Sfly3sQLs7tRkzC4Pz6MCqox3sbbPAdW4t09rgTY0nkQzqzkur8/C5qlZYlU4HqvE4xjOyMWlXfP7hkQFY/Q4HkaL4F101rN8oRcEy5VqKI3U/cAEfR5uRHemnrdk68vzkGaeC1OyFpvpuo5Sr4ut3it2aS6PiZQTgub2CmEFArDEXwWWmdyzw52myQYP3wOGf7vZhl2xihUEkzUj7IIrfamgWdn0KT09c4oqQqOxTCQVsRB7B4YjpASQD942k03zokx6TBW3NNBk/0AM2Aytx4i93EglOhzNs98WKMiTmsxkin0MB/P5YzcdBMpH0J9bESs2P6UWF7eZ2/2pETgHlvkj0qX1T/3E+RNc7OgApr466IgWtLtuuD5AuEBMB/cmP5cC3NbOAiufur0Y1l/pVLZkA/WiXCWJcjM1WHOV5wV6qXU96ufIuuutQPOVaSM+/IHKj8VN10QYxan8TTsxEgX9VRNESqPsmD9NhaYMrZ+mbZW3v0="
    # GA_TOKEN
    - GA_TOKEN: UA-76864579-2
    # LEANCLOUD_ID
    - LEANCLOUND: X0Uz4jdNqtk7pz5GfmX9tm4F-gzGzoHsz
    # LEANCLOUD_KEY
    - secure: "TFOelhLscr7yluKdrCrYFDxnMmgWAcPMTwlfzn/MvhIASWuy7N+5/hsasBXXimF7VfmzsC03qCR5q9hqC1h0iQACOCQocR/2OIZVbmtixCb2BCFFGkrhSLs81SNmXbOi0nNs93LlRVtxwrbM0g4Onm9aRBWgOWCZcdrGy1XjblX8QD47FTwzWFhf2t/Ouy+Gdq5UAOLypsuGrSznPfvWWnuk5v78knD5XuhErSNU1tjAGRfReLnhQJokdlh0OIUBzJGycP+kUI4aetX1D4UTzQivWnOmjzumwM2NZW4Q9paIPg2jd+6MDDVcNaD/JEUZ8FMRIB9+Z4rbAIpEgilUQfsY7qOWX1v+xjcQnLLnFr9mqwPuE8LQYut39IhWBBLFgXXIqyRdBi1ZzkE51cNKImSNdCCGGysuHQ01cM/coQEX+gVtMz4uajdQ9WZqe9WFzm6I0IzvF4zAspd6Rw6PJirZmZRhY+2NYKPbrovqe4m3sGwRwYdswM3M2d5PKGxyflTDEatJta3VSl/Xu8nazEi7i/vg46swXVW+6oJHxZBiKpKsmOqSjwZ17DYSm6XkqyWQHx7lHR1YnEL81v6b3Mc1KJRHNHfOfGaVGIHIf5/X5NznEBhLWSprZpNixfeOlcs/IhD60xVq+f+MLdr5+sgLvsQI+sK6QQN0qJ5cWEc="

   
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - hengliang.jia@gmail.com
  on_success: change
  on_failure: always