language: node_js
# node_js: stable
node_js:
  # - "node"
  - "8.6.0"

cache:
  directories:
    - node_modules
    # The `next-door` from `hengliang.github.hexo-theme-next`
    - themes/next-door

before_install: 
  - if [[ `npm -v` != 5.8.0 ]]; then npm i -g npm@5.8.0; fi

install:
  - npm install
  - npm install --save-dev

before_script:  
  - rm -rf themes
  - git clone https://github.com/Hengliang/hexo-theme-next.git --branch hengliang@develop.remote themes/next-door
  - git clone https://github.com/theme-next/theme-next-fastclick themes/next-door/source/lib/fastclick
  - git clone https://github.com/theme-next/theme-next-jquery-lazyload themes/next-door/source/lib/jquery_lazyload
  - git clone https://github.com/theme-next/theme-next-pace themes/next-door/source/lib/pace
  # - sed -i -e 's/#\[GA_TOKEN\]/\$\{GA_TOKEN\}/g' _config.yml
  # - sed -i -e 's/#\[LEANCLOUD_ID\]/\$\{LEANCLOUD_ID\}/g' _config.yml
  # - sed -i -e 's/#\[LEANCLOUD_KEY\]/\$\{LEANCLOUD_KEY\}/g' _config.yml

script:
  - gulp build

after_success:
  - cd public
  - git init
  - git config user.name "hengliang"
  - git config user.email "hengliang.jia@gmail.com"
  - git add .
  - git commit -m "Travis CI build"
  - git push --force "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master
  # if it isn't a user/org page, please replace it with <master:gh-pages>
  - git push --force "https://hengliang:${CODING_TOKEN}@${CODING_PAGE_REF}" master:master
  

branches:
  only:
    - master

# Travis Environment Variables Guild
# https://docs.travis-ci.com/user/environment-variables
env:
  global:
    # Github Environment Variables
    # ----------------------------------------------------------
    # GIT_PAGE_REF
    - GIT_PAGE_REF: github.com/Hengliang/hengliang.github.io
    # GH_TOKEN
    - secure: "P+Rov2CcAyjf0tSGmq+wNnH7OqrzoQF82YLOlFzBNkt7oXHhdFbAJlz4oTfZtaF5F/beJw3KNA+DgUlECdtJc1xBpNIoz5uaqpbHq/aeJc9tltIropCvGJ0MF75E5PmeSmV+a4nEw2CD/QoyxPNpI8Qq/p4NQY69D28T+eiMYClRppEVYaPteFwL7SwYXEVrywTOaZK4hvnuXBO0qZ37sQuQMa4qsj4udbxuMHvHjjqfbZiaDNfFmn+UghMGJYldxC/e4l2jNHd383hPzWhO84K8YFRY3iFHPeHvJhGkDJhkdJziTqyGS272FzFXipBPgNtp2IJeY3bwToy9bMASEoincNY5Fb3GM2e1jJ0K93+yFEgzh0joU6lG5xiI9Su3O6VsbkSXIyB+nfF0cY9Z4uSRu9+DSDF82BvLAoRbucHF0OrvGcFUNpLLYPiWY5drAmx+b4/WwUFKseHG22zV6j1Oqy0C9jm3ux1LIHdIXD2Xlqg7kJAh0ue1VI7jhXxpIkEMJV99tnXEZul5adpKhAjXBsYoH+LmUDgNt6fcdKrTybzNax3wUI7qvqltnA9t8EqPzL1KpQT+VKNMeAN8x0FHohBQ1cT8kE3tERioVUuFpYKss8wLKWU6D3oWQksZ3v4FGLbnXF5czChDbQIbkkRJlBIvVwP9b0d3heSkUm4="

    # Coding Environment Variables
    # ----------------------------------------------------------
    # CODING_PAGE_REF
    - CODING_PAGE_REF: git.coding.net/hengliang/hengliang.coding.io.git
    # CODING_TOKEN
    - secure: "C6XupvKXGdyIxWzG8HnLyjOK/2JborVpmt3QzEmhDSOuLsf3PUl9j69Uu6ISiOarw87Y08W5/xvByPkr2X/hvqr1RGeMVx7irzJLmR0qVxnRERCkw/TKVqOVXGtFQ0SHCIfeVDmRwne17zWguOLq4fzobBTj2s0aApBSlQH7PR8YIKcGVX0OyrkMJVYO7SK302+Bz2BdBlkpytYJq3tNARoBjDNnxSO5Nc3FSmzAtsGck+5t2G21D7ExIAAUP3P9PKkdJCVbJpo+HIny57A/GWXcl+VkxAwiQ2Mi5JBa9YmdVHyP/fU1qrItUAHOcRszZWjxHqWyBTOUAscOnAeD6LJEl5kZ1DrN1Ot7YunputoWag5TkWyhkkzFxZnWxaHRSPGmX6JWnx9cAV2cGc7BlTOXpETCe1GVFxp9MEmkbLaAYNPsAzdkf4U99MsT06XyErdq3c1pdztqabPYW4Z6fo++wot+CkM4+eY+kGn1mdRddXXVOqL5DeugR21TZHwSrSsdgNBIvqorgy7rAxJ3M16Xs8ua3LcioP89Nl8koxyKe8luBQwS6JglSRKlYFYcOzsC8XeOBe1gaoJ8iyOzC6S5BOrKInMuGffIQrLcubIMUPfDOIvA0F6aTRlHl6YwxvQ8eU8G62CGA/DGHbWZADQ+6WWgAgt1IypZfOt1aqs="

    # Third Party Services Environment Variables
    # ----------------------------------------------------------
    # GA_TOKEN
    # - GA_TOKEN: UA-76864579-2
    # LEANCLOUD_ID
    # - LEANCLOUND: X0Uz4jdNqtk7pz5GfmX9tm4F-gzGzoHsz
    # LEANCLOUD_KEY
    # - secure: "TFOelhLscr7yluKdrCrYFDxnMmgWAcPMTwlfzn/MvhIASWuy7N+5/hsasBXXimF7VfmzsC03qCR5q9hqC1h0iQACOCQocR/2OIZVbmtixCb2BCFFGkrhSLs81SNmXbOi0nNs93LlRVtxwrbM0g4Onm9aRBWgOWCZcdrGy1XjblX8QD47FTwzWFhf2t/Ouy+Gdq5UAOLypsuGrSznPfvWWnuk5v78knD5XuhErSNU1tjAGRfReLnhQJokdlh0OIUBzJGycP+kUI4aetX1D4UTzQivWnOmjzumwM2NZW4Q9paIPg2jd+6MDDVcNaD/JEUZ8FMRIB9+Z4rbAIpEgilUQfsY7qOWX1v+xjcQnLLnFr9mqwPuE8LQYut39IhWBBLFgXXIqyRdBi1ZzkE51cNKImSNdCCGGysuHQ01cM/coQEX+gVtMz4uajdQ9WZqe9WFzm6I0IzvF4zAspd6Rw6PJirZmZRhY+2NYKPbrovqe4m3sGwRwYdswM3M2d5PKGxyflTDEatJta3VSl/Xu8nazEi7i/vg46swXVW+6oJHxZBiKpKsmOqSjwZ17DYSm6XkqyWQHx7lHR1YnEL81v6b3Mc1KJRHNHfOfGaVGIHIf5/X5NznEBhLWSprZpNixfeOlcs/IhD60xVq+f+MLdr5+sgLvsQI+sK6QQN0qJ5cWEc="

   
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - hengliang.jia@gmail.com
  on_success: change
  on_failure: always